version: "3.8"

services:
  server:
    build:
      context: ./server
      dockerfile: Dockerfile
    restart: unless-stopped
    env_file: ./server/.env
    networks:
      - picz
    ports:
      - "3001:3001" # for backend
      - "5555:5555" # for prisma studio
    volumes:
      - ./server:/app
      - /app/node_modules
    command: npm run dev

  client:
    build:
      context: ./client
      dockerfile: Dockerfile
    restart: unless-stopped
    env_file: ./client/.env
    networks:
      - picz
    ports:
      - "5173:5173"
    volumes:
      - ./client:/app
      - /app/node_modules
    command: sh -c "npm rebuild && npm run dev -- --host"

  postgres:
    image: postgres:12
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
      POSTGRES_DB: piczDB
    networks:
      - "picz"
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

networks:
  picz:
    driver: bridge

volumes:
  postgres_data:
