name: Frontend CI

on:
  push:
    branches:
      - main
      - development
  pull_request:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build Docker image
        run: |
          docker build --platform linux/arm64 -t sunnyeyles/picz-client:1 -f ./client/Dockerfile ./client

      - name: Run container with env variables
        run: |
          docker run --rm --platform linux/arm64 \
            -e VITE_API_URL=${{ secrets.VITE_API_BASE_URL }} \
            -p 5173:5173 \
            sunnyeyles/picz-client:1
